= i3blocks-status
:toc:

This project provides scripts for i3blocks to copycat the status line generated by i3status.

CAUTION: Any block or option not available in i3status is out of scope.

The default configuration file is a direct translation of the default i3status configuration file.
With i3blocks link:https://vivien.github.io/i3blocks/#_installation[set up], you can fetch these scripts and run them with:

[source]
----
git clone https://github.com/vivien/i3blocks-status.git ~/.config/i3blocks
i3blocks # or from another location with -c i3block-status/config
----

General options are described below.

== +general+

TODO

Blocks (i3status "modules") are described below.

== +battery+

TODO

== +cpu_temperature+

TODO

== +cpu_usage+

TODO

== +ddate+

TODO

== +disk+

TODO

== +ethernet+

TODO

== +ipv6+

TODO

== +load+

TODO

== +path_exists+

TODO

== +run_watch+

TODO

== +time+

TODO

== +tztime+

TODO

== +volume+

TODO

== +wireless+

Get the link quality, frequency, and ESSID of the given wireless network interface.

.Options
[horizontal]
+instance+:: Network interface (defaults to +_first_+)
+format_up+:: Format string when the interface is up. +
Placeholders can be: +%bitrate+, +%essid+, +%frequency+, +%ip+, +%quality+.
+format_down+:: Format string when the interface is down.

.Example
[source,ini]
----
[wireless]
instance=wlan0
format_up=W: (%quality at %essid, %bitrate / %frequency) %ip
format_down=W: down
----
