#!/bin/bash

set -e

# Required a single argument
if [ $# -ne 1 ]
then
	cat <<EOF
Usage: ${0##*/} TITLE

For a more thorough description, please refers to i3-status man page.

EOF
	exit 1
fi >&2

# Setup default values
format="${format:-%Y-%m-%d %H:%M:%S %Z}"
# timezone is not set
# locale is not set
# format_time is not set

# Set full text format string
fulltext_format="$format"

# Export timezone
if [[ $timezone ]]
then
	TZ="$timezone"
	export TZ
fi

# Export locale
if [[ $locale ]]
then
	LC_ALL="$locale"
	export LC_ALL
fi

# Time format?
if ! [[ $format_time ]]
then
	# Update full text (first line)
	date "+$format"
	exit
fi

# Compute time placeholder value
_time="$(date "+$format_time")"

# Update full text (first line)
eval "$(echo "echo \"${fulltext_format//%/\$_}\"")"
